name: Multi-Platform Health Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        container: [ubuntu:latest, debian:latest, rockylinux:9, almalinux:9, alpine:latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment info
        run: |
          echo "OS: ${{ matrix.os }}" >> healthlog.txt
          echo "Container: ${{ matrix.container }}" >> healthlog.txt
          echo "--------------------------------" >> healthlog.txt
          uname -a >> healthlog.txt || ver >> healthlog.txt
          docker --version >> healthlog.txt || echo "Docker not available" >> healthlog.txt
          echo "" >> healthlog.txt

      - name: Run basic commands
        run: |
          echo "Running system health checks..." >> healthlog.txt
          echo "Date: $(date)" >> healthlog.txt
          echo "Disk usage:" >> healthlog.txt
          df -h >> healthlog.txt || echo "Disk check skipped" >> healthlog.txt
          echo "" >> healthlog.txt

      - name: Upload individual log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: healthlog-${{ matrix.os }}-${{ matrix.container }}
          path: healthlog.txt

  combine-results:
    runs-on: ubuntu-latest
    needs: [health-check]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all logs
        uses: actions/download-artifact@v4
        with:
          path: ./logs

      - name: Combine all logs
        run: |
          echo "===== Combined Health Logs =====" > healthlog.txt
          for file in $(find ./logs -type f -name "*.txt"); do
            echo "Merging $file ..." >> healthlog.txt
            echo "" >> healthlog.txt
            cat "$file" >> healthlog.txt
            echo "" >> healthlog.txt
            echo "--------------------------------" >> healthlog.txt
          done

      - name: Commit and push healthlog.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add healthlog.txt
          git commit -m "Auto-update healthlog.txt [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload zip (backup)
        if: failure() || always()
        run: zip -r healthlog.zip healthlog.txt

      - name: Upload zipped backup
        uses: actions/upload-artifact@v4
        with:
          name: healthlog-backup
          path: healthlog.zip
